/**
 * App-owned mirrors of the Postgres enum types (formerly generated by `@prisma/client` from
 * schema.prisma's `enum` blocks). Members and casing verified directly against the live database's
 * `pg_enum` catalog — must stay in sync with the `CREATE TYPE ... AS ENUM (...)` definitions.
 */

export const UserRole = {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    SUPERVISOR: 'SUPERVISOR',
    EMPLOYEE: 'EMPLOYEE',
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const PlatformAdminRole = {
    SUPER_ADMIN: 'SUPER_ADMIN',
} as const;
export type PlatformAdminRole = (typeof PlatformAdminRole)[keyof typeof PlatformAdminRole];

export const ProductionStage = {
    EXTRUDER: 'EXTRUDER',
    LOOMS: 'LOOMS',
    FABRIC_CHECKING: 'FABRIC_CHECKING',
    DELIVERY: 'DELIVERY',
} as const;
export type ProductionStage = (typeof ProductionStage)[keyof typeof ProductionStage];

export const ProductionRecordType = {
    NORMAL: 'NORMAL',
    ADJUSTMENT: 'ADJUSTMENT',
    REVERSAL: 'REVERSAL',
} as const;
export type ProductionRecordType = (typeof ProductionRecordType)[keyof typeof ProductionRecordType];

export const ProductionType = {
    PRODUCTION: 'PRODUCTION',
    SAMPLE: 'SAMPLE',
} as const;
export type ProductionType = (typeof ProductionType)[keyof typeof ProductionType];

export const InventoryType = {
    HDPE: 'HDPE',
    CHEMICAL: 'CHEMICAL',
    COLOR: 'COLOR',
} as const;
export type InventoryType = (typeof InventoryType)[keyof typeof InventoryType];

export const Gender = {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    OTHER: 'OTHER',
} as const;
export type Gender = (typeof Gender)[keyof typeof Gender];

export const AttendanceStatus = {
    DAY_SHIFT: 'DAY_SHIFT',
    NIGHT_SHIFT: 'NIGHT_SHIFT',
    ABSENT: 'ABSENT',
    HALF_DAY: 'HALF_DAY',
    COMPANY_HOLIDAY: 'COMPANY_HOLIDAY',
} as const;
export type AttendanceStatus = (typeof AttendanceStatus)[keyof typeof AttendanceStatus];

export const KoraEntryType = {
    CREDIT: 'CREDIT',
    DEBIT: 'DEBIT',
} as const;
export type KoraEntryType = (typeof KoraEntryType)[keyof typeof KoraEntryType];

export const RightAction = {
    VIEW: 'VIEW',
    ADD: 'ADD',
    EDIT: 'EDIT',
    DELETE: 'DELETE',
} as const;
export type RightAction = (typeof RightAction)[keyof typeof RightAction];
